[package]
name = "posts"
version = "0.1.0"
edition = "2021"

[dependencies]
firework = { git = "https://www.github.com/whattss/firework", features = [] }
tokio = { version = "1", features = ["full"] }
linkme  = "0.3"
